### PR TITLE
Remove note since in practice we have a 1.1 branch

### PR DESCRIPTION
**Pull request by ianbjacobs**
***
<a href="https://pr-preview.s3.amazonaws.com/w3c/payment-request/pull/1001.html" title="Last updated on Nov 14, 2022, 2:50 PM UTC (a2c749f)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/payment-request/1001/d62abb5...a2c749f.html" title="Last updated on Nov 14, 2022, 2:50 PM UTC (a2c749f)">Diff</a>

### CODE REVIEW

**Review by marcoscaceres — APPROVED** [review]

**Comment by marcoscaceres** [comment]
Having said that... it would be good if the versioning now went away entirely.

**Comment by marcoscaceres** [comment]
@ianbjacobs, just a quick reminder to always add "Editorial:" to commit messages when merging. 🙏 Then ReSpec knows to omit those commit messages from the change log in the spec itself.

**Comment by ianbjacobs** [comment]
Oops. Thank you for the reminder. Can it be added after the fact?

**Comment by marcoscaceres** [comment]
> Can it be added after the fact?

It can, but it makes a mess for anyone that's forked the repo (as their main branch history will no longer match).

**Pull request merged**
