### PR TITLE
chore: Prepare PR branch

### PR DESCRIPTION
**Pull request by marcoscaceres**
Prepares for Proposed Recommendation. Date values subject to change.

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/payment-request/pull/860.html" title="Last updated on Dec 11, 2019, 10:13 PM UTC (f3f7994)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/payment-request/860/4d8ed23...f3f7994.html" title="Last updated on Dec 11, 2019, 10:13 PM UTC (f3f7994)">Diff</a>

### CODE REVIEW

**Comment by marcoscaceres** [comment]
We will need to adjust the dates as we know more...

**Review by ianbjacobs — COMMENTED** [review]
This seems fine, noting that we'll likely need to change the dates.

**Comment by marcoscaceres** [comment]
Ok,  cool. We can keep changing the date as needed.

**Comment by marcoscaceres** [comment]
Closing this... @ianbjacobs, I think it would be good to republish a CR after #908 goes in. The TR version is getting stale again and it seems unlikely we will finish this spec before the end of the year.

**Pull request closed without merging**
