### PR TITLE
show() must be triggered by user activation

### LINKED ISSUE #651: Require user gesture when `.show()` is called
> If interoperable behavior emerges amongst user agents, then that behavior will be standardized here before progressing the specification along the W3C Recommendation Track.

It looks like this is already noted in the CR, but I wanted to open a ticket for this to track status on this. 

ApplePayJS (whose behavior I imagine will eventually make it into Safari's PaymentRequest implementation) only allows `.show()` to be called by user activation (e.g. `click`). On the other hand, Chrome allows `.show()` to be called as long as the page is in focus. This makes it hard to build consistent UIs.

### PR DESCRIPTION
**Pull request by marcoscaceres**
closes #651

The following tasks have been completed:

 * [X] [web platform tests](https://github.com/w3c/web-platform-tests/pull/9990)
 * [x] [MDN Docs added](https://developer.mozilla.org/en-US/docs/Web/API/PaymentRequest/show) 

Implementation commitment:

 * [x] Safari (already in WebKit)
 * [x] [Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=817807)
 * [x] [Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1442078)
 * [ ] Edge (public signal)

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/payment-request/pull/655.html" title="Last updated on Mar 14, 2018, 12:43 AM GMT (a9cc8ba)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/payment-request/655/463d25c...a9cc8ba.html" title="Last updated on Mar 14, 2018, 12:43 AM GMT (a9cc8ba)">Diff</a>

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Note that this has significant impact on the test suite. So, once we have agreement we will need to deal with that before merging.

**Review by domenic — APPROVED** [review]
Spec text changes LGTM; unsure of consensus status.

**Comment by rsolomakhin** [comment]
We can implement this only after show promise. (Otherwise some merchants will break.) Landing the spec change is OK.

**Comment by marcoscaceres** [comment]
@rsolomakhin, ok, good to know... Let's try land them together.

**Comment by marcoscaceres** [comment]
This is implemented in WebKit already. Added link to Gecko bug. @rsolomakhin, do you have a bug number for Chrome?

**Comment by marcoscaceres** [comment]
Rebased... bit rot.

**Comment by marcoscaceres** [comment]
[I've updated MDN](https://developer.mozilla.org/en-US/docs/Web/API/PaymentRequest/show).

**Comment by rsolomakhin** [comment]
[Chrome bug link](https://crbug.com/817807).

**Comment by marcoscaceres** [comment]
Quick update... I've changed the necessary WPTests to be manual. Just waiting on reviews and we should be good to merge. Marking a blocked on those.

**Review by rsolomakhin — APPROVED** [review]

**Comment by marcoscaceres** [comment]
Ok, tests are updated, so feel ok about merging this.

**Comment by marcoscaceres** [comment]
@ianbjacobs, could you please send a request to republish the document?

**Review by rsolomakhin — COMMENTED** [review]
Looks good!

**Pull request merged**
