### PR TITLE
Add reference to issue #45.

### PR DESCRIPTION
**Pull request by msporny**
Add reference to issue #45.

### CODE REVIEW

**Comment by adrianhopebailie** [comment]
@msporny I think this would be better placed in the Payment Method Identifiers spec and even better as a concrete proposal alongside the two current proposals.

https://w3c.github.io/browser-payment-api/specs/method-identifiers.html

**Comment by msporny** [comment]
Issue #45 isn't just about Payment Method Identifiers, but Payment Requests and responses as well. Happy to put a concrete proposal together alongside the current proposals in the Payment Method Identifier spec, but that's not the only place this issue marker belongs. 

I'm not going to be able to put together a concrete proposal for the Payment Method Identifier spec in the next 48 hours (and process all the other requests for PR changes). Happy to re-word this issue, but I need some guidance on what would be acceptable to the group. Would this work?

> There is a discussion on whether or not payment messages and the data they contain should have a more formal and extensible description format than WebIDL, such as JSON-LD or JSON Schema. This is being tracked in issue #45.

Would something like that work?

**Comment by adrianhopebailie** [comment]
@msporny that suggested text makes no sense to me because it doesn't reflect what is being discussed in #45.

At a minimum I think you need to re-title the issue thread. 

I think what you are suggesting is that all payment method data keys and payment method identifiers themselves should be rooted in a linked data vocab and (maybe) that the payment data object passed to the payment request should be expressed in something more extensible than WebIDL.

**Comment by adrianhopebailie** [comment]
@msporny 

I'd like to close this PR unless you still wish to address my comments above?

**Pull request closed without merging**
