### PR TITLE
Spread resolved `data` on updateWith()

### PR DESCRIPTION
**Pull request by marcoscaceres**
This builds on https://github.com/w3c/payment-request/pull/668 to allow incremental data updates as proposed in #649.

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/payment-request/pull/669.html" title="Last updated on Jan 19, 2018, 5:19 AM GMT (fc5ea16)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/payment-request/669/fe1a3ca...fc5ea16.html" title="Last updated on Jan 19, 2018, 5:19 AM GMT (fc5ea16)">Diff</a>

### CODE REVIEW

**Comment by marcoscaceres** [comment]
@domenic, the interesting stuff only happens in https://github.com/w3c/payment-request/pull/669/commits/fc5ea166c04eec1f642fcdc2b60c3070973065ab. The rest is just #668.

**Review by domenic — CHANGES_REQUESTED** [review]
So it's better to stay at the Infra level than to drop down to the ECMAScript level. Otherwise what happens here will be different if someone monkeys with Object.prototype, for example. You'll need to define some kind of ordered map merging operation, or let us do that for you in Infra.

BUT, as I pointed out in https://github.com/w3c/payment-request/issues/649#issuecomment-359108225, I don't think this patch is necessary at all. Let's continue discussing there.

**Comment by marcoscaceres** [comment]
Confirmed, not needed. Sorry about the noise. Someone needs to fire the person writing test tho :)

**Comment by marcoscaceres** [comment]
@domenic, I'm still kinda wondering if we should add "property spread" to infra (even if we didn't need it here). 

Consider, after validation the `values` object, it would be nice to just spread them over `request.[[details]]` instead of adding/replacing the properties one by one.

**Comment by domenic** [comment]
Yeah, I definitely think some kind of "merge-with-overwrite" for ordered maps would be reasonable. I'd prefer to wait until we have a consumer, but we could open a tracking issue perhaps.

**Pull request closed without merging**
