### PR TITLE
Add optional description to PaymentShippingOption

### LINKED ISSUE #902: Proposal to add optional "description" string field to PaymentShippingOption dictionary
Payment apps supporting shipping delegation and/or use agents can use the merchant provided description field to show more details about each shipping option upon user interaction (e.g. when user hovers over the shipping option label)

### PR DESCRIPTION
**Pull request by marcoscaceres**
closes #902

The following tasks have been completed:

 * [X] Confirmed there are no ReSpec errors/warnings.
 * [ ] Modified Web platform tests (link)
 * [ ] Modified MDN Docs (link)
 * [ ] Has undergone security/privacy review (link)
 
Implementation commitment:

 * [ ] Safari (link to issue)
 * [ ] Chrome (link to issue)
 * [ ] Firefox (link to issue)
 * [ ] Edge (public signal)

Optional, impact on Payment Handler spec?

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/payment-request/pull/910.html" title="Last updated on May 22, 2020, 8:09 AM UTC (19a0e64)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/payment-request/910/482e698...19a0e64.html" title="Last updated on May 22, 2020, 8:09 AM UTC (19a0e64)">Diff</a>

### CODE REVIEW

**Review by rsolomakhin — APPROVED** [review]

**Comment by marcoscaceres** [comment]
@rsolomakhin, is this something you will plan on supporting in Chrome (or already support)?

**Comment by marcoscaceres** [comment]
Blocking on implementer interest... I don't mind adding this to Firefox if it will be helpful to pass along to a payment handler.

**Comment by rsolomakhin** [comment]
@sahel-sh - do we still have interest from payment handlers for this field?

**Comment by sahel-sh** [comment]
Sorry I missed this earlier.
The initial PH asking for this is no longer interested; However, I still think that this is still a nice addition to have specially since multiple Android apps have expressed interest in shipping address delegation.

**Comment by marcoscaceres** [comment]
No more shipping stuff thanks to #955 ... can now be done with private data

**Pull request closed without merging**
