### PR TITLE
Losen requirements around Credit Card required fields

### PR DESCRIPTION
**Pull request by mattsaxon**
Removed incorrect required fields as per issue 134

### CODE REVIEW

**Comment by zkoch** [comment]
Hey Matt, cardholder name being optional makes sense because of rationale provided in #134, but can you explain expiration dates also being optional?

**Comment by mattsaxon** [comment]
UnionPay debit cards don't have an expiry date.

**Comment by adrianhopebailie** [comment]
@zkoch why would we enforce this at the API level anyway?

To me this IDL simply provides a standardized data model for the payment app to hang data off so that the website (or PSP) that gets the response knows where to find things. If we are too restrictive we will force people to write new payment method specs to simply change a field from mandatory to optional.

A question for @zkoch and @adrianba (or any other browser vendor) is whether you expect the browser to do any validation of this data when it comes back from a third-party payment app? I expected it to be entirely opaque.

**Comment by halindrome** [comment]
Frankly, this is my problem with using WebIDL as a way of representing a data model.  IDL isn't _for_ data modelling (I speak as someone who was on that committee at OMG back in the day).  It was _for_ defining APIs that may be connected asynchronously over a network - especially when the different ends of that connection might be in differing programming languages.  It represents a contract.

In this case the contract is between the payee and the payment app for the important parts of the data.  And we are in no position to enforce nor even negotiate that contract.  At least, I don't think we are.  It is too fluid.

**Comment by adrianhopebailie** [comment]
@halindrome that is why I suggested we don't use WebIDL in these specs in #132

@AxelNennker is opposed to changing from WebIDL so I suggest we put the issue up for discussion on a future call. I'll see what the priorities look like for this week and add it if we have time.

**Comment by adrianba** [comment]
This change LGTM.

**Pull request merged**
