### PR TITLE
Add a reference to issue #39

### PR DESCRIPTION
**Pull request by msporny**
Add a reference to issue #39.

### CODE REVIEW

**Comment by zkoch** [comment]
I don't think issues around registration belong in the paymentrequest spec. @ianbjacobs addresses this in his draft blog post, so I think that might be good enough for now.

**Comment by adrianhopebailie** [comment]
@zkoch I don't think this is about registration it's about integration between the user agent and a web based payment app.

@msporny For consistency, I think the issue markers for issues #50, #39 should follow a similar format as they both relate to payment app interface (one for native apps and the other for web based apps).

I would suggest the following text and would include this at an appropriate point in the section [User Agent delegates payment request algorithm](https://w3c.github.io/browser-payment-api/specs/paymentrequest.html#user-agent-delegates-payment-request-algorithm) and possibly another reference in the [complete()](https://w3c.github.io/browser-payment-api/specs/paymentrequest.html#complete) section as this refers to messages being passed back to the payment app.

Suggested text:

``` html
<p class="issue" data-number="39" title="It is unclear how the user agent will interface with 
a web-based payment app.">The architecture document suggests that payment apps may 
take numerous forms, including as web-based apps. This specification should describe how 
the user-agent will pass the payment request data and the complete signal to a web-based 
payment app and also how it will receive the payment response from the payment app.</p>
```

**Comment by msporny** [comment]
> I would suggest the following text and would include this at an appropriate point in the section User Agent delegates payment request algorithm

Done, used your text and preferred location.

**Comment by adrianba** [comment]
Merged as 188ae18bff7d6fe592c866f09d9c2900d4beb2b0

**Pull request closed without merging**
