### PR TITLE
Update transient activation to match WebKit

### PR DESCRIPTION
**Pull request by marcoscaceres**
Update the spec to match what WebKit does. We can then update Chrome to match.

The following tasks have been completed:

 * [x] [Modified Web platform tests](https://github.com/web-platform-tests/wpt/pull/30006)
  
Implementation commitment:

 * [X] Safari - already implemented
- [ ]  [Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=1239453) 

Optional, impact on Payment Handler spec?

none

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/payment-request/pull/961.html" title="Last updated on Aug 13, 2021, 3:32 AM UTC (9362883)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/payment-request/961/41c87b0...9362883.html" title="Last updated on Aug 13, 2021, 3:32 AM UTC (9362883)">Diff</a>

### CODE REVIEW

**Review by rsolomakhin — APPROVED** [review]

**Review by ianbjacobs — APPROVED** [review]

**Review by stephenmcgruer — APPROVED** [review]
I tried to find some prior art here on whether to throw a NotAllowed or SecurityError, and came up short 😂 . What I did find:

1. webusb and webbluetooth throw a SecurityError
1. One other spec I found threw NotAllowedError, but most other specs just quietly return or ignore calls/etc when there is no activation.
1. We [used to](https://github.com/w3c/payment-request/pull/885/files) throw SecurityError, then [switched](https://github.com/w3c/payment-request/pull/916/files) to NotAllowedError without documented reason that I could find.

So... SecurityError LGTM? Maybe something the web should standardize on ;)

**Comment by marcoscaceres** [comment]
> So... SecurityError LGTM? Maybe something the web should standardize on ;)

I've asked for this too elsewhere, but wasn't successful... as you point out, it's somewhat specific to the API (and if the API throws/rejects or can get away with doing nothing).

**Comment by marcoscaceres** [comment]
Could someone please also approve the tests? 🙏 https://github.com/web-platform-tests/wpt/pull/30006

**Comment by marcoscaceres** [comment]
@stephenmcgruer, filed Chrome bug https://bugs.chromium.org/p/chromium/issues/detail?id=1239453

Happy to send a patch, but please see my email as I'm not sure how to enable the right flag to trigger that code path.

**Pull request merged**
