### PR TITLE
editorial: IDL dictates what is/isn't required (closes #408)

### LINKED ISSUE #408: Is 'currencySystem' required?
[The spec says](https://w3c.github.io/browser-payment-api/#paymentcurrencyamount-dictionary):

> The following fields are required:
> `currencySystem`...

However, the WebIDL for `currencySystem` does not have the `required` keyword. Let's change the phrasing of the spec to make it clear that `currencySystem` is optional. The developer could, for example, not specify it, or specify `currencySystem: null` or `currencySystem: undefined`, correct?

### PR DESCRIPTION
**Pull request by marcoscaceres**
***
[Preview](https://s3.amazonaws.com/pr-preview/w3c/browser-payment-api/required-fields.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/browser-payment-api/40c760b...7d9a550.html)

### CODE REVIEW

**Comment by marcoscaceres** [comment]
@rsolomakhin r?

**Comment by marcoscaceres** [comment]
@ianbjacobs, could you kindly add rsolomakhin as a collaborator to the repo? that way we can assign reviews.. There are also a few other key folks that need to be added (e.g., Tommy, Domenic, etc.).

**Comment by ianbjacobs** [comment]
Added @tommythorsen, @rsolomakhin, and @domenic (who is not a participant in the WG formally speaking, so heads-up).

**Review by domenic — APPROVED** [review]

**Comment by marcoscaceres** [comment]
Taking r+ from @domenic for this one. Post-merge comments always welcome.

**Pull request merged**
