### PR TITLE
fix: disallow duplicate PMIs when creating request

### LINKED ISSUE #905: Disallow ambiguous methodData declarations?
In my Masters' thesis, I found a set of issues with the Web Payment APIs (see #903 for further reference). This is one of the mentioned issues.

The current specification allows for methodData declarations that have the following form:

```
const methodData = [
  {
    supportedMethods: "https://example.com/bobpay",
    data: {
      merchantIdentifier: "XXXX",
      bobPaySpecificField: true,
    },
  },
  {
    supportedMethods: "https://example.com/bobpay",
    data: {
      merchantIdentifier: "YYYY",
      bobPaySpecificField: true,
    },
  },
];
```
Such an ambiguous methodData declaration (two different entries for a single payment method identifier), is not further discussed by the spec. 
If a payment handler and/or the trusted payment UI are inconsistent regarding which entry they use, this might have serious implications (such as diferent merchants receiving the payment).
This especially holds true for potential future named payment methods such as basic-card.

In case of the declaration of modifiers, the spec offers a "last-one-wins" approach.
I advocate that such ambiguous methodData declarations should not be allowed at all, at the very least they should be mentioned to raise awareness. 
In my opinion they should lead to an erroneous case on payment request creation.

### PR DESCRIPTION
**Pull request by marcoscaceres**
closes #905

The following tasks have been completed:

 * [X] Confirmed there are no ReSpec errors/warnings.
 * [X] [Modified Web platform tests](https://github.com/web-platform-tests/wpt/commit/8bdfc7451d7ad917ebabefc3bedab5f49e0eee5d)
 * [X] Modified MDN Docs - edge case, let's not bother. 
 * [X] Has undergone security/privacy review - part of #905
 
Implementation commitment:

 * [x] [Safari](https://bugs.webkit.org/show_bug.cgi?id=220824)
 * [x] [Chrome](https://crbug.com/1085712)
 * [x] [Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1633344)
 * [ ] Edge (public signal)

Optional, impact on Payment Handler spec?

None.

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/payment-request/pull/908.html" title="Last updated on May 22, 2020, 9:41 AM UTC (af76701)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/payment-request/908/f868c93...af76701.html" title="Last updated on May 22, 2020, 9:41 AM UTC (af76701)">Diff</a>

### CODE REVIEW

**Comment by marcoscaceres** [comment]
We have a patch ready to go on the Firefox side... @edenchuang was also wondering what we should do about duplicate payment method modifiers for the same PMI... we have a last one wins algo there, the maybe we should start throwing for those too (we can do that as a followup).

**Comment by danyao** [comment]
> We have a patch ready to go on the Firefox side... @edenchuang was also wondering what we should do about duplicate payment method modifiers for the same PMI... we have a last one wins algo there, the maybe we should start throwing for those too (we can do that as a followup).

I went to look for why we decided on "last one wins" before and found these two threads:
https://github.com/w3c/payment-request/issues/684
https://github.com/w3c/payment-request/pull/581

IIUC, the main thrust for supporting multiple modifiers for the same PMI is because of `basic-card`. A merchant may want to specify a different modifier for different `supportedNetworks` of `basic-card`.

While I think it'll be conceptually cleaner if the spec treats method data and method modifier consistently, the `basic-card` use case seems legitimate. So I think we should keep the current "last one wins" algorithm and not throw.

**Comment by marcoscaceres** [comment]
This is now implemented in Gecko and we added a Web Platform test for it: https://github.com/web-platform-tests/wpt/commit/8bdfc7451d7ad917ebabefc3bedab5f49e0eee5d 

@danyao or @rsolomakhin, would you mind providing a tracking chrome bug? I think then we are good to merge this.

**Comment by marcoscaceres** [comment]
> While I think it'll be conceptually cleaner if the spec treats method data and method modifier consistently, the basic-card use case seems legitimate. So I think we should keep the current "last one wins" algorithm and not throw.

Agree, with respect to modifiers.

**Comment by rsolomakhin** [comment]
https://crbug.com/1085712

**Comment by marcoscaceres** [comment]
Awesome! @danyao, do you want to give this a last review? I need a ✅ to merge.

**Review by danyao — APPROVED** [review]
LGTM!

**Comment by marcoscaceres** [comment]
Was fixed in WebKit by https://bugs.webkit.org/show_bug.cgi?id=220824

**Comment by ianbjacobs** [comment]
Thanks!!

**Pull request merged**
