### PR TITLE
Remove merchant validation

### LINKED ISSUE #927: What should we do with MerchantValidationEvent?
Right now, `MerchantValidationEvent` is a Safari only feature. Should `MerchantValidationEvent` be "at risk" or can we get a second implementation? There seemed to be some level of commitment on the Chrome side but seems it hasn't shipped:
https://bugs.chromium.org/p/chromium/issues/detail?id=867904

### PR DESCRIPTION
**Pull request by marcoscaceres**
closes #927 

The following tasks have been completed:

 * [X] Confirmed there are no ReSpec errors/warnings.
 * [ ] [Modified Web platform tests](https://github.com/web-platform-tests/wpt/pull/25693)
 
Implementation commitment:

 * [ ] Safari - Shipping
 * [ ] Chrome - Never implemented
 * [ ] Firefox - Never shipped

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/payment-request/pull/929.html" title="Last updated on Sep 23, 2020, 7:49 AM UTC (7b8ae54)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/payment-request/929/345eb6f...7b8ae54.html" title="Last updated on Sep 23, 2020, 7:49 AM UTC (7b8ae54)">Diff</a>

### CODE REVIEW

**Review by danyao — APPROVED** [review]

**Comment by marcoscaceres** [comment]
Couple of things we need to do before merging:

 * @ianbjacobs will create a new repo "merchant-validation" 
 * Marcos needs to move the WPTests out of the payment-request/ to a new folder in WPT and mark the tests as tentative.

**Comment by ianbjacobs** [comment]
@marcoscaceres, new repo for you:
 https://github.com/w3c/merchant-validation

**Comment by marcoscaceres** [comment]
Unofficial draft of merchant validation at https://w3c.github.io/merchant-validation/

**Comment by marcoscaceres** [comment]
Moved the tests out of main payment request directory: https://github.com/web-platform-tests/wpt/pull/25693

**Comment by ianbjacobs** [comment]
Thanks, @marcoscaceres!

**Pull request merged**
