### PR TITLE
Do not show payment requests for non-fully-active documents

### LINKED ISSUE #360: Need to define the interaction of payment API with navigation and browsing context destruction
I don't see anything in the spec that describes what happens if any of the following happen while a payment request is in progress:

1. Navigation to a different happens in the browsing context which contains the document/window that the payment request was created in.
2. Navigation happens in some ancestor browsing context.
3. The browsing context which contains the document/window the payment request was created in is torn down (e.g. iframe removed from the DOM).
4. Some ancestor browsing context is torn down (e.g. tab which contains an iframe that made a payment request is closed).

Part of the issue here, of course, is that there is a bit of a lack of spec clarity around what happens to event listeners and Promises when these things happen.  But even apart from that, it's not clear what should happen to the UA-provided payments UI when these things happen.  It's also not clear what happens if these things happen between the user dismissing the browser-provided UI (e.g. accepting the payment) and the "user accepts the payment request algorithm" running.

### PR DESCRIPTION
**Pull request by domenic**
Closes #360.

***
[Preview](https://s3.amazonaws.com/pr-preview/w3c/payment-request/bc-funtimes.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/payment-request/343fe47...b6c3f94.html)

### CODE REVIEW

**Review by marcoscaceres — APPROVED** [review]

**Comment by domenic** [comment]
Anyone able to bypass the IPR checker and get this merged?

**Comment by marcoscaceres** [comment]
Was hoping to get some tests written before merge. Been doing that with other PRs lately (i.e., "no tests, no merge" policy).

**Comment by marcoscaceres** [comment]
@ianbjacobs No problem that this was merged, but now that we are more or less in CR, it's important that we don't let anything untested slip through! 

So, 🎸🎶If the label is yellow and it says "needs tests", 🥁, "then mellow and don't merge... Ooooh!! sing it with me! Don't merge untested things! YYEAhhh!"🎶 🎸.

**Comment by marcoscaceres** [comment]
Filed WPT bug so we don't forget: 
https://github.com/w3c/web-platform-tests/issues/6930

If anyone wants to be a true hero, here is your chance...  ☝️

**Comment by marcoscaceres** [comment]
Incoming test for this for anyone interested https://github.com/w3c/web-platform-tests/issues/7240

**Pull request merged**
