### PR TITLE
editorial: fix links to tests

### LINKED ISSUE #630: 404 on some tests
Some tests got renamed, but I forgot to update the links in the spec... reminding myself to do that.

### PR DESCRIPTION
**Pull request by marcoscaceres**
closes #630

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/payment-request/pull/691.html" title="Last updated on Mar 7, 2018, 2:24 AM GMT (3283980)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/payment-request/691/463d25c...3283980.html" title="Last updated on Mar 7, 2018, 2:24 AM GMT (3283980)">Diff</a>

### CODE REVIEW

**Comment by marcoscaceres** [comment]
@zcorpan I linked all the tests you wrote.... but I'm unsure about the ".sub." files. Is there one file that runs all the sub frame files, or does "sub" mean something else?

**Comment by zcorpan** [comment]
Sub is same as ?pipe=sub, enables substitutions in wptserve.

**Comment by marcoscaceres** [comment]
I’ve no idea what that does, tbh😊 I’ll read up, but in the meantime let me know if the tests I listed of yours are ok. I added all the HTML files in that directory. I also checked the links are ok.

**Comment by marcoscaceres** [comment]
I replaced the feature policy test (as we don't have a normative requirement on feature policy in this version of the spec), and instead I'm pointing to the `allowpaymentrequest` tests that throw a `SecurityError`.

**Comment by marcoscaceres** [comment]
Merging this, as it's not particularly critical and just editorial.

**Pull request merged**
