### PR TITLE
codemod user agent to payment mediator in payment request

### PR DESCRIPTION
**Pull request by rvm4**
addresses issue #103

### CODE REVIEW

**Comment by adrianba** [comment]
Note that #103 refers to the architecture document. Also, I'm not sure a global replacement of user agent into payment mediator is what is needed here. For example, it definitely is a user agent that implements the IDL interfaces.

**Comment by ianbjacobs** [comment]
@adrianba,

> Also, I'm not sure a global replacement of user agent into payment mediator is what is needed here.

That sounds likely. The intent (in my mind) is to clarify roles (so "global replace" may not be the right way to do that.)

Ian

**Comment by adrianhopebailie** [comment]
:+1: to @ianbjacobs and @adrianba 

I think we need to clearly separate the concerns. The user agent is performing two roles, as payment mediator and also as data collection mediator (facilitating the optimized checkout flow).

I have proposed splitting the API document into two to acheive this in #138

**Comment by adrianhopebailie** [comment]
@adrianba said (and @ianbjacobs concurred): 

> I'm not sure a global replacement of user agent into payment mediator is what is needed here

I agree. This document is probably the wrong place to make these changes.

**Pull request closed without merging**
