### PR TITLE
Rename `PayerErrorFields` to `PayerErrors`

### LINKED ISSUE #782: Rename `PayerErrorFields` to be like `AddressErrors` and `BasicCardErrors`
`AddressErrors` and `BasicCardErrors` both end in "Errors" but `PayerErrorFields` doesn't and I also find that name a bit confusing (should it have been `PayerFieldErrors`?). It would be nice to have consistency and rename to `PayerErrors` (or `PayerFieldErrors` if `PayerErrors` is too confusing).

### PR DESCRIPTION
**Pull request by akansha2608**
closes #782 

The following tasks have been completed:

 * [ ] Confirmed there are no ReSpec errors/warnings.
 * [x] <del>Modified Web platform tests</del> IDL is automatically updated. 
 * [ ] Modified MDN Docs (link)

Implementation commitment:

 * [x] [Safari](https://bugs.webkit.org/show_bug.cgi?id=191213)
 * [x] [Chrome](https://bugs.chromium.org/p/chromium/issues/detail?id=890660)
 * [x] [Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1495335)
 * [ ] Edge (public signal)

Optional, Impact on Payment Handler spec?

***
<a href="https://pr-preview.s3.amazonaws.com/akansha2608/payment-request/pull/789.html" title="Last updated on Nov 2, 2018, 9:44 PM GMT (75c2b9e)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/payment-request/789/3b6a1ac...akansha2608:75c2b9e.html" title="Last updated on Nov 2, 2018, 9:44 PM GMT (75c2b9e)">Diff</a>

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Thanks @akansha2608. Two little things: please be sure to retain the pull request template, as all tasks listed there need to be completed before we can merge. I've added it back above so we can work through it. Also, please use "@marcoscaceres" not @marcos-travel - as that's just an account I use while traveling.

So, to start, when you open "index.html" from your local file system, can you confirm there are no errors or warnings next to the "ReSpec" button at the top of right of the spec?  
  
Secondly, you need to check that `PayerErrorFields` doesn't appear on MDN (we might be lucky and it's not yet documented). But please confirm. If it's not documented, then we need to document it. 

Lastly, we need to get implementation commitment from various browsers. 

@aestes, @romandev or @rsolomakhin, minor bike shedding change? You all ok with this change?

**Review by marcoscaceres — APPROVED** [review]
Rename looks good.

**Comment by marcoscaceres** [comment]
Marked as non substantive for IPR from ash-nazg.

**Comment by marcoscaceres** [comment]
Firefox tracking bug https://bugzilla.mozilla.org/show_bug.cgi?id=1495335

**Comment by romandev** [comment]
Chromium tracking bug: https://bugs.chromium.org/p/chromium/issues/detail?id=890660

**Comment by akansha2608** [comment]
> Thanks @akansha2608. Two little things: please be sure to retain the pull request template, as all tasks listed there need to be completed before we can merge. I've added it back above so we can work through it. Also, please use "@marcoscaceres" not @marcos-travel - as that's just an account I use while traveling.
> 
Hi , thanks for the review , i will make sure from next time , its done totally by mistake.


> So, to start, when you open "index.html" from your local file system, can you confirm there are no errors or warnings next to the "ReSpec" button at the top of right of the spec?
> 
Hi @marcoscaceres , I checked the `index.html` on my local system , there is no errors or warnings near  `ReSpec` button . Also attached screenshot for the same :)


> Secondly, you need to check that `PayerErrorFields` doesn't appear on MDN (we might be lucky and it's not yet documented). But please confirm. If it's not documented, then we need to document it.
> 
Yes we are lucky its not documented https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/PayerErrorFields, do we need to create another issue for the same? :smile: 


screenshot_2018-10-01 payment request api

**Comment by marcoscaceres** [comment]
> do we need to create another issue for the same?

@akansha2608, no, we generally just do it as part of this issue and then check the box at the top when it's done. 

I'm seeing at least one mention of `PayerErrorFields` here:
https://developer.mozilla.org/en-US/search?q=PayerErrorFields&topic=apps&topic=html&topic=css&topic=js&topic=api&topic=canvas&topic=svg&topic=webgl&topic=mobile&topic=webdev&topic=http&topic=webext&topic=standards

Could you kindly please update it?

**Comment by akansha2608** [comment]
> I'm seeing at least one mention of `PayerErrorFields` here:
> https://developer.mozilla.org/en-US/search?q=PayerErrorFields&topic=apps&topic=html&topic=css&topic=js&topic=api&topic=canvas&topic=svg&topic=webgl&topic=mobile&topic=webdev&topic=http&topic=webext&topic=standards
> 
> Could you kindly please update it?

Hi @marcoscaceres i updated this.

Can you guide me through first about first about documentation please :) How to do that?

**Comment by marcoscaceres** [comment]
> Can you guide me through first about first about documentation please :) How to do that?

Will follow up on Slack.

**Comment by marcoscaceres** [comment]
Merging this so it's easier to do the docs

**Comment by aestes** [comment]
WebKit tracking bug: https://bugs.webkit.org/show_bug.cgi?id=191213

**Pull request merged**
