### PR TITLE
Add reference to issue #46.

### PR DESCRIPTION
**Pull request by msporny**
Add reference to issue #46.

### CODE REVIEW

**Comment by adrianba** [comment]
This issue should be flagged in the method-identifiers.html document like issues #10 and #11.

**Comment by adrianba** [comment]
See 3c528926467fe574db98926e55037840608f83e0

**Comment by msporny** [comment]
-1 for closing this issue. I raised this PR to help the reader understand that we're still discussing payment method identifiers while they're reading the Payment Request API spec. They wouldn't understand that payment method identifiers are under active discussion unless they went and read the Payment Method spec and I don't think we can hope that folks that read the specs read all of them to understand the lay of the land. We can't get the WG to read all the specs as it is.

**Comment by ianbjacobs** [comment]
I agree that we need readers to understand that there are active discussions on a variety of topics. But I think we should make life simpler for readers by conveying that a small number of times, and not overloading them with redundant issue flags.

So for example, in the Payment Request API spec section "3. Dependencies" we would add a statement like: "Note: Each of the specifications published by this Working Group includes issue flags where the group is seeking input."

I also expect to write a blog post framing all the publications and letting people know that there are issues and questions for feedback in each of the specs. (I'll discuss that at today's call.)

Ian

**Pull request closed without merging**
