### PR TITLE
Set [[waitForUpdate]] to true on dispatch of payerdetailchange

### LINKED ISSUE #854: [[waitForUpdate]] must be set to true always after dispatch.
Elsewhere, @danyao wrote: 

> From my reading of the spec, [[waitForUpdate]] is only set to true after updateWith() is called. Am I missing something?

Yes, indeed a small spec bug. Will send a patch.

### PR DESCRIPTION
**Pull request by marcoscaceres**
closes #854

The following tasks have been completed:

 * [X] Confirmed there are no ReSpec errors/warnings.
 * [X] [Modified Web platform tests](https://github.com/web-platform-tests/wpt/pull/16164) 
 * [ ] Modified MDN Docs (link)
 * [ ] Has undergone security/privacy review (link)
 
Implementation commitment:

 * [ ] Safari (link to issue)
 * [ ] [Chrome](https://crbug.com/947938)
 * [x] Firefox - already implemented. 
 * [ ] Edge (public signal)

Optional, impact on Payment Handler spec?

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/payment-request/pull/857.html" title="Last updated on Apr 3, 2019, 4:32 PM UTC (34dad90)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/payment-request/857/eda31d8...34dad90.html" title="Last updated on Apr 3, 2019, 4:32 PM UTC (34dad90)">Diff</a>

### CODE REVIEW

**Review by romandev — APPROVED** [review]
lgtm

**Review by danyao — APPROVED** [review]
LGTM!

**Comment by marcoscaceres** [comment]
@romandev or @danyao, thanks for the review! Will merge, but could you please link to a Chrome bug for tracking purposes above?

**Comment by romandev** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=947938

**Comment by rsolomakhin** [comment]
Thank you @romandev! We missed you at the face-to-face :-D

**Pull request merged**
