### PR TITLE
Create pr-preview config file.

### PR DESCRIPTION
**Pull request by tobie**
(Using https://tobie.github.io/pr-preview/config.html)

This still requires someone from @w3c to install the [PR preview integration](https://github.com/integration/pr-preview). Either for all org repos (opt-in to using it by adding a config file like this one), or just for this one.

### CODE REVIEW

**Comment by marcoscaceres** [comment]
@dontcallmedom or @ianbjacobs, would you be so kind as to install it: https://github.com/integration/pr-preview

**Comment by marcoscaceres** [comment]
(would be awesome if it was globally installed for the whole W3C organization, btw... the PR diff tools seems very useful)

**Comment by sideshowbarker** [comment]
> would you be so kind as to install it: https://github.com/integration/pr-preview

Installed and showing up at https://github.com/w3c/browser-payment-api/settings/installations

Also changed your perms for the repo to Admin so if the PR preview tool doesn’t seem to be work as expected, feel free to troubleshoot ti

**Comment by marcoscaceres** [comment]
Thanks @sideshowbarker!

**Comment by tobie** [comment]
FYI: there were huge AWS outages yesterday which affected pr-preview greatly. Not sure how stable things are right now. So do expect some disturbance.

**Comment by marcoscaceres** [comment]
Yeah, it's still pretty bad out there... Travis CI is still struggling ATM.

**Comment by sideshowbarker** [comment]
Amazing distributed system we’ve spent all these years creating technologies for! Would be a crazy situation if instead our only choice in practice was among just two or three giant vendors and they all run into different major outages relatively regularly. Imagine that!

**Pull request merged**
