### PR TITLE
Add regionCode attribute to PaymentAddress (1.1)

### LINKED ISSUE #65: ContactAddress 'region' inconsistencies
I'm having a number of issues integrating our checkout with the payment request API when it comes to shipping options / shipping address forms. These centre around the address 'region', e.g. 'CA' in the US. 

**Project info / requirement**
To give some background, I have a requirement to have shipping options that are available to certain regions within a country. This could be for legal reasons, e.g. in the US, only being able to ship certain goods to certain states. I must therefore, verify user inputted address region values against our shipping options when determining which shipping options to pass to the payment request interface.

**Lack of 'region' input**
Depending on the country however, sometimes the region is mandatory (US, Australia), optional (Ireland), missing (Qatar). Can this field be mandatory for all countries? (i.e. we would need 'region' to be mandatory in all cases so we can verify our shipping options against the user's country and state)

**Inconsistency of input type and value**
For both address forms that could be used, i.e. billing and shipping, the value retrieved from the user is not in a consistent format, in terms of input type and response value. On web browsers (as far as I've tested), the region is a dropdown. However, depending on the country, the value returned is not consistent, e.g. it's a 2 letter code such as 'CA' for the US, state name such as 'Delhi' for India, and 'Co. Dublin' for Ireland. 

On mobile browsers (and possibly some web, but generally mobile), the 'region' is a free form input, so the customer could enter anything essentially, e.g. 'CA', 'California', 'Californnn'. In this case, we have no direct solution for mapping this value.

**Overall solution proposal**
- 'Region' is mandatory.
- 'Region' returns the state as a 2 letter code (ISO 3166-2), from a pre-defined set of values.

### LINKED ISSUE #663: ContactAddress 'region' inconsistencies
I'm having a number of issues integrating our checkout with the payment request API when it comes to shipping options / shipping address forms. These centre around the address 'region', e.g. 'CA' in the US. 

**Project info / requirement**
To give some background, I have a requirement to have shipping options that are available to certain regions within a country. This could be for legal reasons, e.g. in the US, only being able to ship certain goods to certain states. I must therefore, verify user inputted address region values against our shipping options when determining which shipping options to pass to the payment request interface.

**Lack of 'region' input**
Depending on the country however, sometimes the region is mandatory (US, Australia), optional (Ireland), missing (Qatar). Can this field be mandatory for all countries? (i.e. we would need 'region' to be mandatory in all cases so we can verify our shipping options against the user's country and state)

**Inconsistency of input type and value**
For both address forms that could be used, i.e. billing and shipping, the value retrieved from the user is not in a consistent format, in terms of input type and response value. On web browsers (as far as I've tested), the region is a dropdown. However, depending on the country, the value returned is not consistent, e.g. it's a 2 letter code such as 'CA' for the US, state name such as 'Delhi' for India, and 'Co. Dublin' for Ireland. 

On mobile browsers (and possibly some web, but generally mobile), the 'region' is a free form input, so the customer could enter anything essentially, e.g. 'CA', 'California', 'Californnn'. In this case, we have no direct solution for mapping this value.

**Overall solution proposal**
- 'Region' is mandatory.
- 'Region' returns the state as a 2 letter code (ISO 3166-2), from a pre-defined set of values.

### PR DESCRIPTION
**Pull request by marcoscaceres**
Revert "Remove regionCode attribute (#823)"
This reverts commit 5906b72b2e8c500c31144c36db7c8e4eeabb555f.

closes w3c/contact-picker#65

The following tasks have been completed:

 * [ ] Confirmed there are no ReSpec errors/warnings.
 * [ ] [Modified Web platform tests](https://github.com/web-platform-tests/wpt/pull/15501)
 * [ ] Modified MDN Docs (link)
 * [ ] Has undergone security/privacy review (link)
 
Implementation commitment:

 * [x] [Safari](https://bugs.webkit.org/show_bug.cgi?id=197392)
 * [ ] [Chrome](https://crbug.com/817960)
 * [ ] Firefox - partial implementation - supports the attribute. 
 * [ ] Edge (public signal)

Optional, impact on Payment Handler spec?

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/payment-request/pull/836.html" title="Last updated on Sep 21, 2020, 3:34 PM UTC (3bab5bc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/payment-request/836/a4f35e3...3bab5bc.html" title="Last updated on Sep 21, 2020, 3:34 PM UTC (3bab5bc)">Diff</a>

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/payment-request/pull/836.html" title="Last updated on Jun 27, 2023, 10:59 PM UTC (3bab5bc)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/payment-request/836/a4f35e3...3bab5bc.html" title="Last updated on Jun 27, 2023, 10:59 PM UTC (3bab5bc)">Diff</a>

### CODE REVIEW

**Comment by rsolomakhin** [comment]
Is this for 1.0 or 1.1+?

**Comment by marcoscaceres** [comment]
1.1

**Comment by marcoscaceres** [comment]
Blocked on release of 1.0.

**Comment by marcoscaceres** [comment]
Ok, tests and spec are resurrected for when when want this...

**Comment by marcoscaceres** [comment]
@danyao or @rsolomakhin, if you have a bug on the Chromium side, could you please add it to the top of the bug?

**Comment by rsolomakhin** [comment]
Linked the Chrome bug.

**Review by rsolomakhin — APPROVED** [review]
For when you need to merge it in the future.

**Comment by marcoscaceres** [comment]
Mucho appreciated!

**Comment by Abdulmanahtalib** [comment]
Tw

**Comment by marcoscaceres** [comment]
Similarly here, we need commitment from another implementer to land this.

**Comment by marcoscaceres** [comment]
No moar PaymentAddress with w3c/payment-request#955

**Pull request closed without merging**
