### PR TITLE
fix: give PaymentMethodChangeEventInit defaults

### LINKED ISSUE #770: Can PaymentMethodChangeEventInit really have a required member?
Can PaymentMethodChangeEventInit really have a required member given that it is optional in the event constructor?

See:
https://w3c.github.io/payment-request/#dom-paymentmethodchangeeventinit
https://w3c.github.io/payment-request/#paymentmethodchangeevent-interface

### PR DESCRIPTION
**Pull request by marcoscaceres**
closes #770 

The following tasks have been completed:

 * [X] Confirmed there are no ReSpec errors/warnings.
 * [x] Modified Web platform tests (link)
 * [x] Modified MDN Docs (link)

Implementation commitment:

 * [ ] [Safari](https://bugs.webkit.org/show_bug.cgi?id=189100)
 * [ ] Chrome (link to issue)
 * [ ] [Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1487295)
 * [ ] Edge (public signal)

Optional, Impact on Payment Handler spec?

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/payment-request/pull/771.html" title="Last updated on Sep 4, 2018, 7:39 AM GMT (ddfc88a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/payment-request/771/138a787...ddfc88a.html" title="Last updated on Sep 4, 2018, 7:39 AM GMT (ddfc88a)">Diff</a>

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Added gecko [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1487295). Will write a test to make sure it defaults correctly.

**Comment by aestes** [comment]
I'm implementing all of PaymentMethodChangeEvent in this [WebKit bug](https://bugs.webkit.org/show_bug.cgi?id=189100), so I'll update my patch with this change before landing.

**Review by aestes — APPROVED** [review]

**Review by domenic — APPROVED** [review]
LGTM, but might also want to add a `= null` for methodDetails. I don't think it has any normative effect, but it seems like the trend is to have defaults for all event-init dictionaries?

**Comment by marcoscaceres** [comment]
Tests will be upstreamed from Gecko once the Firefox patch lands.

**Comment by marcoscaceres** [comment]
Ok, sent request to merge on the Firefox side and asked our awesome tech writers to document this change.

**Comment by marcoscaceres** [comment]
Spec is republished on TR.

**Pull request merged**
