### PR TITLE
throw if updateWith() is not trusted

### LINKED ISSUE #546: Unstrusted events can update PaymentRequest
Unless I've missed something, it seems one can co-opt and untrusted event to do the work of a trusted event*:

```JS
const request = new PaymentRequest(defaultMethods, defaultDetails);
const untrustedEvent = new PaymentRequestUpdateEvent("test"); 
request.dispatchEvent(ev); // set .target
request.show();
request.onshippingaddresschange = () => {
  const update = {
    total: {
      label: "Untrusted",
      amount: {
        currency: "USD",
        value: "1111.00",
      },
    },
  };
  untrustedEvent.updateWith(Promise.resolve(update));
};
```
We might just need to say in `.updateWith()` that if the event is untrusted, throw a `SecurityError` or `NotAllowedError`.

*Chrome ignores this.

### PR DESCRIPTION
**Pull request by marcoscaceres**
* closes #546

***
[Preview](https://s3.amazonaws.com/pr-preview/w3c/browser-payment-api/update_ev_is_trusted.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/browser-payment-api/3b7f783...a6f85f1.html)

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Given the`.isTrusted` assurance from the UA, it follows that: iff the user agent dispatches the event, then the dispatch flag is always set, and the .target is always a `PaymentRequest` on which event was dispatched. 

Therefore, the checks of 8771656 are now redundant.

**Comment by marcoscaceres** [comment]
Oh no... I just read that mouse events can hack around this :) Removing 8771656. Let's see if I can come up with some evil tests using trusted events.

**Comment by marcoscaceres** [comment]
Sorry for the noise... but actually https://github.com/w3c/browser-payment-api/pull/547#issuecomment-307305938 still applies. I got confused :(

**Comment by marcoscaceres** [comment]
Associated tests: https://github.com/w3c/web-platform-tests/pull/6162

**Review by domenic — APPROVED** [review]
Hmm, do you really think NotAllowedError is the right choice? It implies the user denied permission, whereas I don't think permission was ever asked about whether you can update the payment details.

I might go with InvalidStateError.

But, LGTM, I am OK either way. It is borderline.

**Pull request merged**
