### PR TITLE
Minor typographical fixes

### LINKED ISSUE #353: "store" value in [[internalSlot]]
The spec uses terminology like:

> Store details into request@[[details]]. 

But it's not clear what "store" means. We should just "set" internal slots to things.

### PR DESCRIPTION
**Pull request by domenic**
- Fix #353: set slots to values, don't store in slots
- Use `<var>` instead of `<em>` for variables
- Use `<i>` instead of `<em>` for state names
- Don't use `<em>` or `<code>` for literal values like null, undefined, false, and true.
- Run HTML Tidy

### CODE REVIEW

**Comment by marcoscaceres** [comment]
Looks good! thanks @domenic.

**Comment by marcoscaceres** [comment]
D'oh, I'd assume this was the first part - as it come in first.

**Comment by domenic** [comment]
This one first is good! I've rebased #369 and #370, although for some reason #370 is still showing merge conflicts.

**Comment by marcoscaceres** [comment]
Yeah, #370 confused me. Cool.

**Pull request merged**
