### PR TITLE
Add privacy protection to MerchantValidationEvent's validationURL

### PR DESCRIPTION
**Pull request by marcoscaceres**
Part of PING discussions. 

The following tasks have been completed:

 * [X] Confirmed there are no ReSpec errors/warnings.
 * Not testable <del>Modified Web platform tests</del>.
 
Optional, impact on Payment Handler spec?

If handlers will have a means of handling merchant validation, that spec should include a privacy note.

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/payment-request/pull/850.html" title="Last updated on Mar 14, 2019, 1:39 AM UTC (b090589)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/payment-request/850/76135b9...b090589.html" title="Last updated on Mar 14, 2019, 1:39 AM UTC (b090589)">Diff</a>

### CODE REVIEW

**Review by rsolomakhin — APPROVED** [review]
Thank you for the clarification. I will be sure to include this in the PH spec when adding the merchant validation feature and will add you the the PR for review.

**Review by ianbjacobs — CHANGES_REQUESTED** [review]
Hi @marcoscaceres 

I agree with the sentiment, but two things make me uncomfortable:

 * Imposing a normative requirement on payment handlers in this specification.
 * It would probably be ok for the URL to include some information about a person for an authorized server; we don't want that information to be visible to unauthorized parties.

Proposed:

   "It is important that the <a>validationURL</a> in a <a>MerchantValidationEvent</a>
   does not expose personally identifying information to unauthorized parties."

I am avoiding creating a normative requirement, but do want to stress the importance.

**Comment by marcoscaceres** [comment]
@ianbjacobs, your suggestion sounds good. Could you please update this branch with your new text?

**Comment by ianbjacobs** [comment]
Hi @marcoscaceres,

I made the change and also did a tidy; I think some of the changes shown are due to tidy.

Ian

**Pull request merged**
