### PR TITLE
Editorial: fixup updateWith() example

### PR DESCRIPTION
**Pull request by marcoscaceres**
Remove mention of non-existent [[updatedUI]] internal slot. Simplify language a little bit.

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/payment-request/pull/667.html" title="Last updated on Jan 17, 2018, 11:19 PM GMT (74b44a8)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/payment-request/667/fe1a3ca...74b44a8.html" title="Last updated on Jan 17, 2018, 11:19 PM GMT (74b44a8)">Diff</a>

### CODE REVIEW

**Review by ianbjacobs — APPROVED** [review]

**Comment by marcoscaceres** [comment]
@ianbjacobs, could you please send a request to republish the spec?

**Comment by ianbjacobs** [comment]
@marcoscaceres,

Sorry for the delay. I see that a number of (mostly editorial) changes have happened to the main branch since the previous CR update (on 21 Sep 2017 [1]). Should I include all of them? or just this one (#667), or all of them up to and including this one?

Ian

[1] https://www.w3.org/TR/payment-request/

**Comment by marcoscaceres** [comment]
All changes would be great 👍

**Comment by ianbjacobs** [comment]
@marcoscaceres,

Here's the draft I was looking at:
 https://rawgit.com/w3c/payment-request/876a9cc21836c7d2b0fe27f17837cee7da63b664/index.html?specStatus=CR

There are 2 respec warnings:
    Found linkless element with text 'displayitems' but no matching <dfn>.
    Found linkless element with text 'additionaldisplayitems' but no matching <dfn>.

Would you mind fixing those first? Thanks!

Ian

**Comment by marcoscaceres** [comment]
> Would you mind fixing those first? Thanks!

Fixed! Thanks for letting me know. 

PS: Alternative is to grab the tip from https://w3c.github.io/payment-request/?specStatus=CR

**Comment by ianbjacobs** [comment]
Thanks; will send publication request.
Ian

**Comment by marcoscaceres** [comment]
@ianbjacobs let's get https://github.com/w3c/payment-request/pull/671 merged first :)

**Pull request merged**
