### PR TITLE
Reject acceptPromise on abort()

### PR DESCRIPTION
**Pull request by adrianba**
Add the missing step from the abort() method to reject acceptPromise as reported by @adamroach.

### CODE REVIEW

**Comment by zkoch** [comment]
LGTM

**Comment by adrianhopebailie** [comment]
@adamroach Does this address your concerns? If so, please +1 and the editors can merge

**Comment by adamroach** [comment]
LGTM -- +1

**Comment by adrianba** [comment]
Merged as c10e5bc11280dfd9d1668b4e6793e1a162602997.

**Pull request closed without merging**
