### PR TITLE
chore: rename repo to match shortname

### PR DESCRIPTION
**Pull request by marcoscaceres**
Need to rename the repo, then merge this.

### CODE REVIEW

**Comment by domenic** [comment]
Do we really want to break all those links?? :(

**Comment by marcoscaceres** [comment]
I'd rather break this now before we go to CR and this gets really popular (as more browsers ship). 

We have /TR/ as the canonical for the spec regardless.

**Review by sideshowbarker — APPROVED** [review]

**Comment by ianbjacobs** [comment]
@domenic,

> Do we really want to break all those links?? :(

I agree that's a bummer. I found this by you, however:

   Redirecting GitHub Pages after a repository move
   https://gist.github.com/domenic/1f286d415559b56d725bee51a62c24a7

Is that something we should do for the 4 or so repositories we have renamed?

Ian

**Comment by domenic** [comment]
Yeah, that could work, if you are willing to edit the w3c.github.io page.

**Comment by ianbjacobs** [comment]
@adrianhopebailie did the pull request for four specs, which I merged. Seems to work. Thanks @domenic!

Ian

**Pull request merged**
