### PR TITLE
Separate total from line items.

### LINKED ISSUE #18: Constructor should not include "total" in list of items
This issue comes from WICG/paymentrequest#68.

From the spec:

> There is an open issue about whether the `items` sequence should special-case the last item in the sequence to represent the total.

### PR DESCRIPTION
**Pull request by adrianba**
Fixes #18.

### CODE REVIEW

**Comment by rvm4** [comment]
LGTM

**Comment by msporny** [comment]
+1 to merge as it improves the spec. Why a PaymentItem instead of a CurrencyAmount? Does that mean that someone could do this:

``` javascript
details.total.label = "Grand Total";
```

and expect "Grand Total" to show up on the UI?

**Comment by adrianba** [comment]
@msporny wrote:

> Why a PaymentItem instead of a CurrencyAmount?

Displaying the label is optional but, yes, there are current payment APIs that allow the developer to customise the description of the final total.

**Comment by adrianba** [comment]
Merged as 9ef1dd251089299fe3a50df6ff77f02821f7663f per [telcon](http://www.w3.org/2016/04/28-wpwg-minutes.html#item03).

**Pull request closed without merging**
