### PR TITLE
Editorial: use new language for DOMExceptions (close #375)

### LINKED ISSUE #375: Editorial: use new language for DOMExceptions
E.g. `"InvalidStateError" DOMException` instead of just `InvalidStateError`. See https://github.com/heycam/webidl/pull/250 and the new prose at https://heycam.github.io/webidl/#dfn-create-exception

Related: #314

### PR DESCRIPTION
**Pull request by marcoscaceres**

### CODE REVIEW

**Comment by marcoscaceres** [comment]
@domenic r?

**Review by domenic — CHANGES_REQUESTED** [review]
If you Ctrl+F in the document for the error names you can find that all but two error types are not updated:

- All QuotaExceededError instances
- All NotSupportedError instances
- All AbortError instances

Also, the spec still references DOM4, which does not define these exception types. You closed https://github.com/w3c/browser-payment-api/issues/314, saying it was a dupe of https://github.com/w3c/browser-payment-api/pull/357 which I guess was a typo. But if that's going to be closed then it should be fixed.

Awesome to see the inline cross-spec linking working.

**Comment by marcoscaceres** [comment]
Whoops, I thought I got them all. On it!

**Comment by marcoscaceres** [comment]
>Also, the spec still references DOM4, which does not define these exception types. You closed #314, saying it was a dupe of #357 which I guess was a typo. But if that's going to be closed then it should be fixed.

Fixing now. 

> Awesome to see the inline cross-spec linking working.

I know! I should have added that years ago.

**Comment by marcoscaceres** [comment]
Ok, addressed review comments. Hopefully good to go.

**Review by domenic — APPROVED** [review]

**Pull request merged**
